### PR TITLE
feat: version filters

### PR DESCRIPTION
**Pull request by kboroszko**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/22)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
Please make the comment description... more descriptive ;). I.e. why we're adding them, why only a subset, etc.

> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/22#-:-MkCeQgy2DIjNVw5Zfk5:b7n6ggo)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/pytorch_bigtable/version_filters.py, line 25 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/22#-MkCky_CAJlmT8kHB-gU:-MkCky_DBVtPCgTjhTAl:b-n4ymos) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/071bcacc843930a24163b412a2cc656b11bfe989/plugin/pytorch_bigtable/version_filters.py#L25)):*
> ```Python
> 
>   Args:
>     start: The start of the row range (inclusive).
> ```

Please indicate what the `int` and `datetime` represent - it isn't instantly obvious.
___
*[plugin/pytorch_bigtable/version_filters.py, line 30 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/22#-MkCjPI7BajVxpNa30x-:-MkCjPI7BajVxpNa30x0:b-v6lekj) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/071bcacc843930a24163b412a2cc656b11bfe989/plugin/pytorch_bigtable/version_filters.py#L30)):*
> ```Python
>     pbt_C.Filter: Filter passing only values' versions from the specified range.
>   """
>   start_timestamp = start if isinstance(start, int) else int(start.timestamp())
> ```

I think `timestamp()` returns the number of seconds since epoch and you're expecting microseconds.

I also think we should have two different functions:
* `timestamp_range()` taking datetime (because the suffix micros makes little sense here)
* `timestamp_range_micros()` taking integers, representing number of microseconds since epoch

Alternatively, have one `timestamp_range()` taking either `datetime`, `float` or `int` and interpret `float` and `int` as number of seconds since epoch, to make it more pythonic. That way, all of this will work as expected (BTW, please add it as a test, too):
```
now = datetime.datetime.now();
assert timestamp_range(now) == timestamp_range(now.timestamp())
```
___
*[plugin/pytorch_bigtable/tests/test_version_filters.py, line 4 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/22#-MkCl6gdBm51A9kWcStQ:-MkCl6gdBm51A9kWcStR:b-8g5d8o) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/071bcacc843930a24163b412a2cc656b11bfe989/plugin/pytorch_bigtable/tests/test_version_filters.py#L4)):*
> ```Python
> # pylint: disable=C0115
> # pylint: disable=W0212
> # pylint: disable=R1732
> ```

Just like with other files, please document what you're disabling and only disable the relevant warnings.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/22)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dopiera)

___
*[plugin/pytorch_bigtable/version_filters.py, line 25 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/22#-MkCky_CAJlmT8kHB-gU:-MkGFMQ-8y0aQu0w_v0b:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/071bcacc843930a24163b412a2cc656b11bfe989/plugin/pytorch_bigtable/version_filters.py#L25)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please indicate what the `int` and `datetime` represent - it isn't instantly obvious.
</blockquote></details>

Done.
___
*[plugin/pytorch_bigtable/version_filters.py, line 30 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/22#-MkCjPI7BajVxpNa30x-:-MkGE_rL4q1xjQ_1MLiM:b-3uzmp1) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/071bcacc843930a24163b412a2cc656b11bfe989/plugin/pytorch_bigtable/version_filters.py#L30)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think `timestamp()` returns the number of seconds since epoch and you're expecting microseconds.

I also think we should have two different functions:
* `timestamp_range()` taking datetime (because the suffix micros makes little sense here)
* `timestamp_range_micros()` taking integers, representing number of microseconds since epoch

Alternatively, have one `timestamp_range()` taking either `datetime`, `float` or `int` and interpret `float` and `int` as number of seconds since epoch, to make it more pythonic. That way, all of this will work as expected (BTW, please add it as a test, too):
```
now = datetime.datetime.now();
assert timestamp_range(now) == timestamp_range(now.timestamp())
```
</blockquote></details>

Agreed. 
I added `timestamp_range` which can accept either a number (`float` or `int`) representing **seconds** since epoch, or `datetimes`.
`timestamp_range_micros` will now accept only a number (`float` or `int`) representing **microseconds** since epoch. 
___
*[plugin/pytorch_bigtable/tests/test_version_filters.py, line 4 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/22#-MkCl6gdBm51A9kWcStQ:-MkCp-4iA5qJZV8FQhDu:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/071bcacc843930a24163b412a2cc656b11bfe989/plugin/pytorch_bigtable/tests/test_version_filters.py#L4)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Just like with other files, please document what you're disabling and only disable the relevant warnings.
</blockquote></details>

Done.

**Review by kboroszko — COMMENTED** [review]
We're adding version filters creation methods, so users can easily specify which versions they would like to include when reading the database. 
We're wrapping in python only a subset of filter creation methods because the filter functionality that we need for this module is very limited. Other filters are expressed by other parts of the API (i.e. column filters are expressed by specifying columns as an argument in `read_rows` method) and user does not need direct access to them.

> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/22#-:-MkGFyvoE50vMu9P03U9:b-3wc052)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dopiera)

**Review by dopiera — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/22)* status: all files reviewed, 3 unresolved discussions (waiting on @dopiera)

**Pull request merged**
