### PR TITLE
use python linter

### PR DESCRIPTION
**Pull request by kboroszko**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/17)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/17)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/.pylintrc, line 1 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/17#-Mk6mIQ217Tv0S1ALuzA:-Mk6mIQ217Tv0S1ALuzB:b6rlcwj) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/e94b87e0a58502d1b658aa24cc405040b9dde348/plugin/.pylintrc#L1)):*
> ```
> # This Pylint rcfile contains a best-effort configuration to uphold the
> ```

How about we download this file via `curl` every time? It has two benefits, I think:
* it will always be up-to-date
* we don't need to think if we should be adding Google's licence header to it

WDYT?
___
*[plugin/ci/check.sh, line 6 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/17#-Mk6mZzKAtLKx9ZSrqbK:-Mk6mZzKAtLKx9ZSrqbL:bwk8sk4) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/e94b87e0a58502d1b658aa24cc405040b9dde348/plugin/ci/check.sh#L6)):*
> ```Shell
> THIS_SCRIPT_DIR=$( cd "$( dirname "$0" )" ; pwd )
> PROJECT_DIR=$( cd "$THIS_SCRIPT_DIR/.." ; pwd )
> PYLINTRC="$PROJECT_DIR/.pylintrc"
> ```

You don't seem to be using this variable.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/17)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dopiera)

___
*[plugin/.pylintrc, line 1 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/17#-Mk6mIQ217Tv0S1ALuzA:-Mk6r2JbCt-3u6TyGPII:b-7rl0jd) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/e94b87e0a58502d1b658aa24cc405040b9dde348/plugin/.pylintrc#L1)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

How about we download this file via `curl` every time? It has two benefits, I think:
* it will always be up-to-date
* we don't need to think if we should be adding Google's licence header to it

WDYT?
</blockquote></details>

done.
___
*[plugin/ci/check.sh, line 6 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/17#-Mk6mZzKAtLKx9ZSrqbK:-Mk6r0AfCxG2pUyK5Ao3:bcfx2on) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/e94b87e0a58502d1b658aa24cc405040b9dde348/plugin/ci/check.sh#L6)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

You don't seem to be using this variable.
</blockquote></details>

right...

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/17)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/ci/check.sh, line 40 at r2](https://reviewable.io/reviews/unoperate/pytorch-cbt/17#-Mk74Vup7RacF0bbrCxR:-Mk74Vup7RacF0bbrCxS:b9vwatk) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/53cc07d4fa23fd313cf5c4b01ce3a9cb8033c39e/plugin/ci/check.sh#L40)):*
> ```Shell
> 
> log "Getting pylintrc"
> curl https://google.github.io/styleguide/pylintrc --output pylintrc
> ```

Shouldn't it be `.pylintrc`? Also, it's a good practice to add `-sSL` flags to `curl` in scripts (so that it doesn't output progress (the output may not be a terminal) (`-s`), but it does output failures (`-S`) and it does follow redirects (`-L`)).

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/17)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dopiera)

___
*[plugin/ci/check.sh, line 40 at r2](https://reviewable.io/reviews/unoperate/pytorch-cbt/17#-Mk74Vup7RacF0bbrCxR:-Mk75bvd6RCmCyBoCuyY:biiul64) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/53cc07d4fa23fd313cf5c4b01ce3a9cb8033c39e/plugin/ci/check.sh#L40)):*
> oes follow redirect
pylist looks for the file with and without '.' at the beginning so it doesn't matter. I added the flags though.

**Review by dopiera — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/17)* status: all files reviewed, 3 unresolved discussions (waiting on @dopiera)

**Pull request merged**
