### PR TITLE
feat: support for in32 and bool

### PR DESCRIPTION
**Pull request by kboroszko**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/37)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/37)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[Dockerfile, line 63 at r2](https://reviewable.io/reviews/unoperate/pytorch-cbt/37#-Mpl2buD4M5LuPjmJA1c:-Mpl2buD4M5LuPjmJA1d:b-j9d4pv) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/b10f36354d88a08e492ee09c3f3aed6a4872a91c/Dockerfile#L63)):*
> ```
> google-cloud-bigtable
> 
> ```
Why do we need this?
___
*[plugin/csrc/bigtable_dataset.cc, line 181 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/37#-Mpg6ieF8qCfrAgdaL13:-Mpl34mJ830CfbzFKJ-e:b-whmr6j) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/8dd6489e9cc0c74f5f214569d1ea76fbb66de918/plugin/csrc/bigtable_dataset.cc#L181)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

pytorch needs the type to be `bool` and xdr requires `bool_t`, hence the static cast.
</blockquote></details>

This `static_cast<>` is now unnecessary, no?

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/37)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dopiera)

___
*[Dockerfile, line 63 at r2](https://reviewable.io/reviews/unoperate/pytorch-cbt/37#-Mpl2buD4M5LuPjmJA1c:-MplDzH65vFVCDmhe5fv:bzhrcbr) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/b10f36354d88a08e492ee09c3f3aed6a4872a91c/Dockerfile#L63)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> google-cloud-bigtable
> 
> ```
Why do we need this?
</blockquote></details>

to test reading from BT we need to upload specific bytes. If we read what we have written, we only check if the implementation is consistent with itself. We also want to check if it is compatible with hbase.
___
*[plugin/csrc/bigtable_dataset.cc, line 181 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/37#-Mpg6ieF8qCfrAgdaL13:-MplEOhE9AqOC-S6_1m0:b-fchu7g) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/8dd6489e9cc0c74f5f214569d1ea76fbb66de918/plugin/csrc/bigtable_dataset.cc#L181)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This `static_cast<>` is now unnecessary, no?
</blockquote></details>

yes.yes it is.

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/37)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/pytorch_bigtable/tests/test_serialization.py, line 31 at r4](https://reviewable.io/reviews/unoperate/pytorch-cbt/37#-MpuwkuGEt_NjfQ3NECe:-MpuwkuGEt_NjfQ3NECf:b-oiuy70) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/cc9af79566a1a152899628b8bc970ad619ec41c9/plugin/pytorch_bigtable/tests/test_serialization.py#L31)):*
> ```Python
> 
> 
> def check_values(test_case, values, table, type_name, dtype):
> ```

Why not make these functions methods of `BigtableSerializationTest`?
___
*[plugin/pytorch_bigtable/tests/test_serialization.py, line 34 at r4](https://reviewable.io/reviews/unoperate/pytorch-cbt/37#-Mpux0_V6KXGoGKS6A18:-Mpux0_V6KXGoGKS6A19:bljzj2p) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/cc9af79566a1a152899628b8bc970ad619ec41c9/plugin/pytorch_bigtable/tests/test_serialization.py#L34)):*
> ```
>     test_case.assertEqual(values[i].item(), r[0].item())
> ```
For floating point types you want `assertAlmostEqual()`, I think. Comparing floats for equality is not a good idea.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/37)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dopiera)

___
*[plugin/pytorch_bigtable/tests/test_serialization.py, line 31 at r4](https://reviewable.io/reviews/unoperate/pytorch-cbt/37#-MpuwkuGEt_NjfQ3NECe:-MpwRaBj1Zmi-LOCp87L:bb6un1j) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/cc9af79566a1a152899628b8bc970ad619ec41c9/plugin/pytorch_bigtable/tests/test_serialization.py#L31)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Why not make these functions methods of `BigtableSerializationTest`?
</blockquote></details>

Done
___
*[plugin/pytorch_bigtable/tests/test_serialization.py, line 34 at r4](https://reviewable.io/reviews/unoperate/pytorch-cbt/37#-Mpux0_V6KXGoGKS6A18:-MpwRcgOCoojXiL94sJE:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/cc9af79566a1a152899628b8bc970ad619ec41c9/plugin/pytorch_bigtable/tests/test_serialization.py#L34)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
>     test_case.assertEqual(values[i].item(), r[0].item())
> ```
For floating point types you want `assertAlmostEqual()`, I think. Comparing floats for equality is not a good idea.
</blockquote></details>

Done.

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/37)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dopiera and @kboroszko)

**Pull request merged**
