### PR TITLE
feat: added parallel reading

### PR DESCRIPTION
**Pull request by kboroszko**
Each worker should first filter the tablets that intersect with the row_set specified by user. Then it calculates it's share of work based on its id and number of workers.

Also, to avoid problems with multiprocessing we create a client every time we perform some operation and close it afterwards. For more information refer to [this issue](https://github.com/Unoperate/pytorch-cbt/issues/23).

---
This change is [Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/24)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/24)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/csrc/bigtable_dataset.cc, line 83 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJPVRiBnGh_yU37Ce0:-MkJPVRiBnGh_yU37Ce1:b-302dkf) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L83)):*
> ```cpp
>   return cbt::CreateDefaultDataClient(std::move(project_id),
>                                       std::move(instance_id),
>                                       cbt::ClientOptions(options));
> ```

`std::move(options)` maybe?
___
*[plugin/csrc/bigtable_dataset.cc, line 137 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJPi8E1SBcF9ItvGE1:-MkJPi8E1SBcF9ItvGE2:b-dkzix9) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L137)):*
> ```cpp
> }
> 
> int GetWorkerStartIndex(int len, int num_workers, int worker_id) {
> ```

Please be more descriptive. I'm guessing `len`  is `num_tablets`? The index is the tablet index, right?

Also, for indices, one usually uses `std::size_t`.

This code is also pretty hard to reason about. How about this:
```
auto div_rounding_up = [](size_t n, size_t d) { return (n + d -1) / d; };
auto const tablets_per_worker = div_rounding_up(num_tablets, num_workers);
return std::min(worker_id * tablets_per_worker, num_tablets);
```

Also, why not make it return a row range:
```
 GetRangeForWorker(, size_t num_workers, size_t worker_id) {
  auto div_rounding_up = [](size_t n, size_t d) { return (n + d -1) / d; };
  auto const tablets_per_worker = div_rounding_up(num_tablets, num_workers);
  auto const range_begin = std::next(tablets.begin(), std::min(worker_id * tablets_per_worker, num_tablets));
  auto const range_end = std::next(tablets.begin(), std::min((worker_id + 1) * tablets_per_worker, num_tablets));
  if (range_begin == range_end) {
    return RowRange.empty();
  }
  auto const last_tablet_in_range = std::prev(range_end);
  return RowRange(range_begin()->start_key
```
___
*[plugin/csrc/bigtable_dataset.cc, line 153 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJT33v865fJMhrk3uS:-MkJT33v865fJMhrk3uT:b62324h) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L153)):*
> ```cpp
> }
> 
> cbt::RowSet CreateRowSet(cbt::RowSet const& row_set,
> ```

Please make the function name more relevant - e.g. `ComputeRowSetForWorker` or something like that.
___
*[plugin/csrc/bigtable_dataset.cc, line 164 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJU0dL7mFwFUvuvT2s:-MkJU0dL7mFwFUvuvT2t:b-yo9cyc) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L164)):*
> ```cpp
>   std::vector<std::pair<std::string, std::string>> filtered;
>   std::string start_key;
>   for (py::handle hand : sample_row_keys) {
> ```

`hand` is pretty misleading. `end_key_handle`?
___
*[plugin/csrc/bigtable_dataset.cc, line 167 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJUYfj5BCF25l3-C5D:-MkJUYfj5BCF25l3-C5E:b-ynlo45) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L167)):*
> ```
> start_key
> ```
`std::move(start_key)` ?
___
*[plugin/csrc/bigtable_dataset.cc, line 173 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJg2FmATaz44rS0Sdm:-MkJg2FmATaz44rS0Sdn:b-hs7lcy) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L173)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>   if (filtered.empty() || !filtered.back().second.empty()) {
>     if (!filtered.empty()) {
>       start_key = filtered.back().second;
>     }
>     if (RowSetIntersectsRange(row_set, start_key, "")) {
>       filtered.emplace_back(start_key, "");
>     }
>   }
> ```
</details>

Wouldn't it be easier to read if you first created a list of all tablets and only then filtered them?
___
*[plugin/csrc/bigtable_dataset.cc, line 182 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJW0Jm8vF-_b2G3gOl:-MkJW0Jm8vF-_b2G3gOm:bwqeynr) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L182)):*
> ```cpp
>   int start = GetWorkerStartIndex(filtered.size(), num_workers, worker_id);
>   int end =
>       GetWorkerStartIndex(filtered.size(), num_workers, worker_id + 1) - 1;
> ```

I think it's a better practice to only subtract this `1` after you know that `end` is larger than `start`. This is because if you use `size_t` you'll wrap the counter.
___
*[plugin/pytorch_bigtable/tests/test_parallel_read.py, line 36 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJgcHm69do6s1jnk9B:-MkJgcHm69do6s1jnk9C:b4xfgbc) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/pytorch_bigtable/tests/test_parallel_read.py#L36)):*
> ```Python
>   def test_read(self):
>     os.environ['BIGTABLE_EMULATOR_HOST'] = self.emulator.get_addr()
>     self.emulator.create_table('fake_project', 'fake_instance', 'test-table',
> ```

Can you please alter the code running the emulator, so that it can create a table with predefined tablets and make the experiment really parallel by utilizing that?

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/24)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/csrc/bigtable_dataset.cc, line 83 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJPVRiBnGh_yU37Ce0:-MkMgLYU-QB0Ji67l0q1:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L83)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

`std::move(options)` maybe?
</blockquote></details>

Done.
___
*[plugin/csrc/bigtable_dataset.cc, line 137 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJPi8E1SBcF9ItvGE1:-MkMlKPq73fXRXlQy7p5:b-pl5ck9) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L137)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please be more descriptive. I'm guessing `len`  is `num_tablets`? The index is the tablet index, right?

Also, for indices, one usually uses `std::size_t`.

This code is also pretty hard to reason about. How about this:
```
auto div_rounding_up = [](size_t n, size_t d) { return (n + d -1) / d; };
auto const tablets_per_worker = div_rounding_up(num_tablets, num_workers);
return std::min(worker_id * tablets_per_worker, num_tablets);
```

Also, why not make it return a row range:
```
 GetRangeForWorker(, size_t num_workers, size_t worker_id) {
  auto div_rounding_up = [](size_t n, size_t d) { return (n + d -1) / d; };
  auto const tablets_per_worker = div_rounding_up(num_tablets, num_workers);
  auto const range_begin = std::next(tablets.begin(), std::min(worker_id * tablets_per_worker, num_tablets));
  auto const range_end = std::next(tablets.begin(), std::min((worker_id + 1) * tablets_per_worker, num_tablets));
  if (range_begin == range_end) {
    return RowRange.empty();
  }
  auto const last_tablet_in_range = std::prev(range_end);
  return RowRange(range_begin()->start_key
```
</blockquote></details>

I disagree. Although the code might be hard to read (fair point, I did my best to improve it), the logic you're proposing would be not optimal. If we just round up the `tablets_per_worker` then the work is not evenly distributed. 

Consider this example: 
We have 100 tablets and 11 workers. `tablets_per_worker` = 10. In that case, the first 10 workers would get 10 tablets each and the last one would be idle.

I'm returning an integer not a RowRange because I want to be able to easily and thoroughly test, what to me is the most crucial part of the logic.

Lastly, I fail to see, how using iterators instead of plain indexes is better. Can you tell me why you're using std::next and not just indices and then vector.at()?
___
*[plugin/csrc/bigtable_dataset.cc, line 164 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJU0dL7mFwFUvuvT2s:-MkMv2EQ-2t60aifR9DD:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L164)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

`hand` is pretty misleading. `end_key_handle`?
</blockquote></details>

Done.
___
*[plugin/csrc/bigtable_dataset.cc, line 167 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJUYfj5BCF25l3-C5D:-MkNFidC5GwfYqnhFTpE:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L167)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> start_key
> ```
`std::move(start_key)` ?
</blockquote></details>

Done.
___
*[plugin/csrc/bigtable_dataset.cc, line 173 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJg2FmATaz44rS0Sdm:-MkMv3w--nFalAmfE2VX:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L173)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
>   if (filtered.empty() || !filtered.back().second.empty()) {
>     if (!filtered.empty()) {
>       start_key = filtered.back().second;
>     }
>     if (RowSetIntersectsRange(row_set, start_key, "")) {
>       filtered.emplace_back(start_key, "");
>     }
>   }
> ```
Wouldn't it be easier to read if you first created a list of all tablets and only then filtered them?
</blockquote></details>

Done.
___
*[plugin/csrc/bigtable_dataset.cc, line 182 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJW0Jm8vF-_b2G3gOl:-MkNEehzEmiAo3DhGBVz:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L182)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think it's a better practice to only subtract this `1` after you know that `end` is larger than `start`. This is because if you use `size_t` you'll wrap the counter.
</blockquote></details>

Done.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/24)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @dopiera)

___
*[plugin/csrc/bigtable_dataset.cc, line 153 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJT33v865fJMhrk3uS:-MkNGIv70TJdzT3TWXtc:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L153)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please make the function name more relevant - e.g. `ComputeRowSetForWorker` or something like that.
</blockquote></details>

Done.
___
*[plugin/pytorch_bigtable/tests/test_parallel_read.py, line 36 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJgcHm69do6s1jnk9B:-MkVhZB43WP3HBoAuhgK:b-sf6ynl) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/pytorch_bigtable/tests/test_parallel_read.py#L36)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Can you please alter the code running the emulator, so that it can create a table with predefined tablets and make the experiment really parallel by utilizing that?
</blockquote></details>

I'd love to, but frankly I couldn't find an option for that either in cbt or in the emulator. If it is in the documentation it must be indeed very well hidden.

I looked through [docs](https://cloud.google.com/bigtable/docs/emulator#using_the_emulator) and through --help pages for both tools. :frowning_face:

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/24)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/csrc/bigtable_dataset.cc, line 137 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJPi8E1SBcF9ItvGE1:-MkTDlBL37hEP9emCRPI:b-mfbjxr) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L137)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

I disagree. Although the code might be hard to read (fair point, I did my best to improve it), the logic you're proposing would be not optimal. If we just round up the `tablets_per_worker` then the work is not evenly distributed. 

Consider this example: 
We have 100 tablets and 11 workers. `tablets_per_worker` = 10. In that case, the first 10 workers would get 10 tablets each and the last one would be idle.

I'm returning an integer not a RowRange because I want to be able to easily and thoroughly test, what to me is the most crucial part of the logic.

Lastly, I fail to see, how using iterators instead of plain indexes is better. Can you tell me why you're using std::next and not just indices and then vector.at()?
</blockquote></details>

Sorry for confusion, please disregard the second part of my comment - I was about to delete it and forgot (having reached the conclusion that it's not better, really).

Regarding the algorithm - you're right - yours is better. Please add a comment explaining why not simply do what I suggested and what yours does.
___
*[plugin/csrc/bigtable_dataset.cc, line 140 at r3](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkTFVMh4gcjzntc7FnH:-MkTFVMh4gcjzntc7FnI:biq4pe0) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/0cf91ce6e91db545a51891d1eb76f6beb8e6a104/plugin/csrc/bigtable_dataset.cc#L140)):*
> ```cpp
>                         size_t worker_id) {
>   if (num_tablets <= num_workers) return std::min(num_tablets, worker_id);
>   size_t rows_per_worker = num_tablets / num_workers;
> ```

nit: s/rows_per_worker/tablets_per_worker/
nit2: please add `const`s to the result of the intermediate calculations
___
*[plugin/pytorch_bigtable/tests/test_parallel_read.py, line 36 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJgcHm69do6s1jnk9B:-MkaYWAY87kL3OgYJyFy:bo5jcp2) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/pytorch_bigtable/tests/test_parallel_read.py#L36)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

I'd love to, but frankly I couldn't find an option for that either in cbt or in the emulator. If it is in the documentation it must be indeed very well hidden.

I looked through [docs](https://cloud.google.com/bigtable/docs/emulator#using_the_emulator) and through --help pages for both tools. :frowning_face: 
</blockquote></details>

```
$ cbt help createtable
cbt createtable <table-id> [families=<family>:gcpolicy=<gcpolicy-expression>,...]
   [splits=<split-row-key-1>,<split-row-key-2>,...]
  families     Column families and their associated garbage collection (gc) policies.
               Put gc policies in quotes when they include shell operators && and ||. For gcpolicy,
               see "setgcpolicy".
  splits       Row key(s) where the table should initially be split

    Example: cbt createtable mobile-time-series "families=stats_summary:maxage=10d||maxversions=1,stats_detail:maxage=10d||maxversions=1" splits=tablet,phone
```

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/24)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dopiera)

___
*[plugin/csrc/bigtable_dataset.cc, line 137 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJPi8E1SBcF9ItvGE1:-MkersQD-R9z12P-f-dR:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/csrc/bigtable_dataset.cc#L137)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Sorry for confusion, please disregard the second part of my comment - I was about to delete it and forgot (having reached the conclusion that it's not better, really).

Regarding the algorithm - you're right - yours is better. Please add a comment explaining why not simply do what I suggested and what yours does.


</blockquote></details>

Done.
___
*[plugin/pytorch_bigtable/tests/test_parallel_read.py, line 36 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkJgcHm69do6s1jnk9B:-Mkez4Mp3g5RSubbCCda:bqjei46) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/9dff1ad07e870246f1ea27525c169ff770104316/plugin/pytorch_bigtable/tests/test_parallel_read.py#L36)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

```
$ cbt help createtable
cbt createtable <table-id> [families=<family>:gcpolicy=<gcpolicy-expression>,...]
   [splits=<split-row-key-1>,<split-row-key-2>,...]
  families     Column families and their associated garbage collection (gc) policies.
               Put gc policies in quotes when they include shell operators && and ||. For gcpolicy,
               see "setgcpolicy".
  splits       Row key(s) where the table should initially be split

    Example: cbt createtable mobile-time-series "families=stats_summary:maxage=10d||maxversions=1,stats_detail:maxage=10d||maxversions=1" splits=tablet,phone
```
</blockquote></details>

Duh, didn't see that... Done. :ok_hand:

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/24)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/csrc/bigtable_dataset.cc, line 359 at r5](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-Mkgot_DDIjA_IaXKbJh:-Mkgot_DDIjA_IaXKbJi:b-hx7xhz) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/3ff5b941ebf5bf24d18a63ec46d2768c3d1ff715/plugin/csrc/bigtable_dataset.cc#L359)):*
> ```cpp
>       .def("__repr__", &PrintRowSet);
> 
>   m.def("get_worker_start_index", &GetWorkerStartIndex,
> ```

Could you please add a comment explaining that we're exporting it to python for testing convenience?
___
*[plugin/csrc/bigtable_dataset.cc, line 364 at r5](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkgoTjw4UOwcWiJ96n-:-MkgoTjw4UOwcWiJ96n0:beqxpni) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/3ff5b941ebf5bf24d18a63ec46d2768c3d1ff715/plugin/csrc/bigtable_dataset.cc#L364)):*
> ```
> create_row_set
> ```
Sorry, I noticed it only now. The name of this python function is pretty confusing - I initially thought it's another ctor. Could you please rename it in the spirit of the C++ function name?
___
*[plugin/pytorch_bigtable/tests/test_parallel_read.py, line 54 at r5](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-Mkgnpql2TzKY804uyN-:-Mkgnpql2TzKY804uyN0:b-1s6luc) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/3ff5b941ebf5bf24d18a63ec46d2768c3d1ff715/plugin/pytorch_bigtable/tests/test_parallel_read.py#L54)):*
> ```Python
> 
>     loader = DataLoader(ds, num_workers=4)
>     for tensor in loader:
> ```

Shouldn't we verify that we read all the rows back without any duplicates?

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/24)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @dopiera)

___
*[plugin/csrc/bigtable_dataset.cc, line 359 at r5](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-Mkgot_DDIjA_IaXKbJh:-MkkTZrv-mhWjONMXTz2:b6e2yhj) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/3ff5b941ebf5bf24d18a63ec46d2768c3d1ff715/plugin/csrc/bigtable_dataset.cc#L359)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Could you please add a comment explaining that we're exporting it to python for testing convenience?
</blockquote></details>

Done. I also changed the name so it starts with "_". This way if anyone uses it outside of tests, the linter will not let that pass.
___
*[plugin/csrc/bigtable_dataset.cc, line 364 at r5](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-MkgoTjw4UOwcWiJ96n-:-MkkSkEB4lUnf7l6fT1i:b21inq0) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/3ff5b941ebf5bf24d18a63ec46d2768c3d1ff715/plugin/csrc/bigtable_dataset.cc#L364)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> create_row_set
> ```
Sorry, I noticed it only now. The name of this python function is pretty confusing - I initially thought it's another ctor. Could you please rename it in the spirit of the C++ function name?
</blockquote></details>

I did. I also fixed the tests' names.
___
*[plugin/pytorch_bigtable/tests/test_parallel_read.py, line 54 at r5](https://reviewable.io/reviews/unoperate/pytorch-cbt/24#-Mkgnpql2TzKY804uyN-:-Mkkax1U-TJ5ef2f75qa:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/3ff5b941ebf5bf24d18a63ec46d2768c3d1ff715/plugin/pytorch_bigtable/tests/test_parallel_read.py#L54)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Shouldn't we verify that we read all the rows back without any duplicates?
</blockquote></details>

Done.

**Review by dopiera — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kboroszko)

**Pull request merged**
