### PR TITLE
feat: support other data types

### PR DESCRIPTION
**Pull request by kboroszko**
This PR adds support for more datatypes. If this approach is accepted, then support for all datatypes possible in pytorch will be added in the next PR.

Also, we expect the user to provide the default value for missing values. Originally we wanted it to just be NaN, then the user can use nan_to_num and replace it to whatever they wish. However, this would not work for tensors with integers, since integers cannot be NaN. instead we ask the user to provide a value, (if the tensor type is float, it can be NaN) and if they don't, the default is 0.

---
This change is [Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/26)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/26)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/csrc/bigtable_dataset.cc, line 49 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-Mkc7Rbn4jLZ715jiG3t:-Mkc7Rbn4jLZ715jiG3u:b-3hi416) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c477300ef4388fb1f83dbae7190bf60c65ae5410/plugin/csrc/bigtable_dataset.cc#L49)):*
> ```cpp
> }
> 
> double BytesToDouble(std::string s) {
> ```

`std::string const&`
___
*[plugin/csrc/bigtable_dataset.cc, line 70 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-Mkc9VE-4uP9BJfSjf2O:-Mkc9VE-4uP9BJfSjf2P:b-3hi416) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c477300ef4388fb1f83dbae7190bf60c65ae5410/plugin/csrc/bigtable_dataset.cc#L70)):*
> ```cpp
> }
> 
> int64_t BytesToInt64(std::string s) {
> ```

`std::string const&`
___
*[plugin/csrc/bigtable_dataset.cc, line 97 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-Mkc9jDv3p6ZKtjvJmin:-Mkc9jDv3p6ZKtjvJmio:b-dssl0r) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c477300ef4388fb1f83dbae7190bf60c65ae5410/plugin/csrc/bigtable_dataset.cc#L97)):*
> ```cpp
> }
> 
> std::string GetTensorValueInBytes(torch::Tensor const& tensor, size_t i,
> ```

nit: s/InBytes/AsBytes/
___
*[plugin/csrc/bigtable_dataset.cc, line 218 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-MkcA0ql1ts3neQ_avcd:-MkcA0ql1ts3neQ_avce:bk0p5fi) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c477300ef4388fb1f83dbae7190bf60c65ae5410/plugin/csrc/bigtable_dataset.cc#L218)):*
> ```cpp
>                           cbt::RowSet const& row_set,
>                           cbt::Filter const& versions,
>                           py::object const& fill_value, int /*num_workers*/,
> ```

Wouldn't `default_value` be a better name? The same applies to other occurrences.

Also, shouldn't this be optional? You could initialize the values with the respective type's default initializer, unless the user has a better idea.

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/26)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/pytorch_bigtable/tests/test_read_rows.py, line 41 at r2](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-MkgqQ3t78qrLE5Ndf1K:-MkgqQ3t78qrLE5Ndf1L:b-lcbmfg) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/3952aae5496f96ff95f684915668b550ecd16aa2/plugin/pytorch_bigtable/tests/test_read_rows.py#L41)):*
> ```Python
>                                     row_range.infinite())):
>       results.append(tensor.reshape(1, -1))
>       print(f"Got tensor: {tensor}")
> ```

I think we should get rid of those prints in tests or at least not add new ones.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/26)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dopiera)

___
*[plugin/csrc/bigtable_dataset.cc, line 49 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-Mkc7Rbn4jLZ715jiG3t:-MkkR5JT8ncYtu6A5P3l:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c477300ef4388fb1f83dbae7190bf60c65ae5410/plugin/csrc/bigtable_dataset.cc#L49)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

`std::string const&`
</blockquote></details>

Done.
___
*[plugin/csrc/bigtable_dataset.cc, line 70 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-Mkc9VE-4uP9BJfSjf2O:-MkkR5q_3m7J881HOlR3:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c477300ef4388fb1f83dbae7190bf60c65ae5410/plugin/csrc/bigtable_dataset.cc#L70)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

`std::string const&`
</blockquote></details>

Done.
___
*[plugin/csrc/bigtable_dataset.cc, line 218 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-MkcA0ql1ts3neQ_avcd:-MkkR70R52m8PkM7nV0V:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c477300ef4388fb1f83dbae7190bf60c65ae5410/plugin/csrc/bigtable_dataset.cc#L218)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Wouldn't `default_value` be a better name? The same applies to other occurrences.

Also, shouldn't this be optional? You could initialize the values with the respective type's default initializer, unless the user has a better idea.
</blockquote></details>

Done.
___
*[plugin/pytorch_bigtable/tests/test_read_rows.py, line 41 at r2](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-MkgqQ3t78qrLE5Ndf1K:-MkkRN1o-TiSQTG-nzc_:bm7r45o) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/3952aae5496f96ff95f684915668b550ecd16aa2/plugin/pytorch_bigtable/tests/test_read_rows.py#L41)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think we should get rid of those prints in tests or at least not add new ones.
</blockquote></details>

Sure. I added assertions, as you can see below. :wink:  I missed these print statements... :ok_man:  deleted now.

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/26)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/csrc/bigtable_dataset.cc, line 199 at r3](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-MklORcx7HAeTJOF8ySH:-MklORcx7HAeTJOF8ySI:bekhv3) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/eed1efaa7bb4ecffa9035dce2dcf775a07282e90/plugin/csrc/bigtable_dataset.cc#L199)):*
> ```cpp
>                  ? torch::full(size, (*default_value).cast<float>(),
>                                torch::TensorOptions().dtype(cell_type))
>                  : torch::full(size, NAN,
> ```

I think it'd be better to initialize it with `float()`, `double()`, etc. They evaluate to zeroes if I'm not mistaken.
___
*[plugin/csrc/bigtable_dataset.cc, line 229 at r3](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-MklN_mw-fgWX0fYST4r:-MklN_mw-fgWX0fYST4s:bqdgbrh) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/eed1efaa7bb4ecffa9035dce2dcf775a07282e90/plugin/csrc/bigtable_dataset.cc#L229)):*
> ```cpp
>                           int /*num_workers*/, int /*worker_id*/)
>       : column_map_(CreateColumnMap(columns)),
>         default_value_(std::move(default_value)),
> ```

Not sure, why `clang-tidy` is not complaining about this, but this move on a cref is probably not what you want.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/26)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dopiera)

___
*[plugin/csrc/bigtable_dataset.cc, line 199 at r3](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-MklORcx7HAeTJOF8ySH:-Mklkw4_As4LWVTefeS4:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/eed1efaa7bb4ecffa9035dce2dcf775a07282e90/plugin/csrc/bigtable_dataset.cc#L199)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think it'd be better to initialize it with `float()`, `double()`, etc. They evaluate to zeroes if I'm not mistaken.
</blockquote></details>

Done.
___
*[plugin/csrc/bigtable_dataset.cc, line 229 at r3](https://reviewable.io/reviews/unoperate/pytorch-cbt/26#-MklN_mw-fgWX0fYST4r:-MklZoLr1OTld_23mxDQ:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/eed1efaa7bb4ecffa9035dce2dcf775a07282e90/plugin/csrc/bigtable_dataset.cc#L229)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Not sure, why `clang-tidy` is not complaining about this, but this move on a cref is probably not what you want.
</blockquote></details>

Done.

**Review by dopiera — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kboroszko)

**Pull request merged**
