### PR TITLE
feat: packaging

### PR DESCRIPTION
**Pull request by kboroszko**
This pr changes the docker image base to manylinux2014 image with CentOS 7.

Another change is to move the C++ extension package inside the pytorch_bigtable package, so it's not just laying around.

Lastly, you may notice we do some magic in the setup.py file. After the extension is built, we run ldd on the .so file to get all the dynamic dependencies and get the location of libssl and libcrypto. We then put them in the build directory so they get included when constructing the wheel. This is discussed in detail in [this issue](https://github.com/Unoperate/pytorch-cbt/issues/27) and mentioned in comments as well.

---
This change is [Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/28)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
nit: s/C/C++/

> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-:-MkqtTKq2t5NJI_gdOMG:bubxvse)* status: 0 of 11 files reviewed, 7 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[Dockerfile, line 15 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkqui7e3f3DQr04lFD0:-Mkqui7e3f3DQr04lFD1:b-3njfvg) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/Dockerfile#L15)):*
> ```Dockerfile
> # limitations under the License.
> 
> # A lot of the code here is "borrowed" from the
> ```

This is all great, but as we spoke, you probably want to retain the ubuntu image as well for `clang-format` and `clang-tidy`.
___
*[plugin/README.md, line 3 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkqv-wEERpM_uok_SqO:-Mkqv-wEERpM_uok_SqP:brtiupx) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/README.md#L3)):*
> ```Markdown
> # Pytorch Bigtable Extension
> 
> This is a Pytorch Extension used to connect to BigTable.
> ```

nit: it's `Bigtable` not `BigTable`. I'd actually write `Google Cloud Bigtable`, which is its full name.
___
*[plugin/setup.py, line 24 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkqvndw3Klys-EamXWQ:-Mkqvndw3Klys-EamXWR:b5x9tz1) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L24)):*
> ```
>  patching
> ```
We're not patching the `*.so` files. We're simply including them in the package, no?
___
*[plugin/setup.py, line 31 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkqw8VXEt1pZCLhhEU_:-Mkqw8VXEt1pZCLhhEUa:b-prm3ep) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L31)):*
> ```
>   What we do instead, is look for the
>   dynamic dependencies not from pytorch manually and then patch them as part
>   of our wheel.
> ```

It's probably not worth the effort, but we could future-proof it by doing the opposite - taking all dependencies which `libtotch.so` does not have.
___
*[plugin/setup.py, line 39 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MkqxMxdAgsuE5kP4Dx2:-MkqxMxdAgsuE5kP4Dx3:b-pf81eq) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L39)):*
> ```Python
>     print("looking for libs")
> 
>     file_list = glob.glob("build/lib*/pytorch_bigtable/pbt_C.cpython*")
> ```

I doubt this will work on Windows anyway, but perhaps, you could future-proof it by using `os.path.join` here, too?
___
*[plugin/setup.py, line 40 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkqwjno0YLs1nIyi-92:-Mkqwjno0YLs1nIyi-93:b-c80482) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L40)):*
> ```Python
> 
>     file_list = glob.glob("build/lib*/pytorch_bigtable/pbt_C.cpython*")
>     so_file_loc = file_list[0]
> ```

That's fishy - if there are more, you'll silently ignore them. Could you please raise an exception if `len(file_list) != 1`?
___
*[plugin/setup.py, line 61 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MkqxeuyAjwKdOSZQsXi:-MkqxeuyAjwKdOSZQsXj:bweyhl6) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L61)):*
> ```
> support@gmail.com
> ```
info@unoperate.com?

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/28)* status: 0 of 17 files reviewed, 7 unresolved discussions (waiting on @dopiera)

___
*[plugin/setup.py, line 24 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkqvndw3Klys-EamXWQ:-Mkvh6nDD2mRcWrvlYub:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L24)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
>  patching
> ```
We're not patching the `*.so` files. We're simply including them in the package, no?
</blockquote></details>

Done.
___
*[plugin/setup.py, line 31 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkqw8VXEt1pZCLhhEU_:-MkvdfrS0xkAlBLN9Vno:b-s5a71d) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L31)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
>   What we do instead, is look for the
>   dynamic dependencies not from pytorch manually and then patch them as part
>   of our wheel.
> ```

It's probably not worth the effort, but we could future-proof it by doing the opposite - taking all dependencies which `libtotch.so` does not have.

</blockquote></details>

If its not worth the effort, should we do it or not? If we're going to perform some sophisticated logic, just to arrive at the conclusion that we have to copy the same two files, maybe we should just skip it? Especially because I don't see a reason why the list of these libraries that we need to include would ever grow. 
___
*[plugin/setup.py, line 39 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MkqxMxdAgsuE5kP4Dx2:-MkvfmGw9v1Z01PALGFz:b-cu0x92) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L39)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I doubt this will work on Windows anyway, but perhaps, you could future-proof it by using `os.path.join` here, too?
</blockquote></details>

I did.

I don't even have a way to test it on windows and I presume the whole build process will have to change. 
We support only linux for now, so maybe it will be worth changing it when we actually start supporting windows?

Or I can add:
```
if os.name != 'posix':
     raise Exception()
```

WDYT?
___
*[plugin/setup.py, line 40 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkqwjno0YLs1nIyi-92:-Mkvh3w2BXpPMqcqjUwQ:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L40)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

That's fishy - if there are more, you'll silently ignore them. Could you please raise an exception if `len(file_list) != 1`?
</blockquote></details>

Done.
___
*[plugin/setup.py, line 60 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkveqcy9VB8gdNeMdOK:-Mkveqcy9VB8gdNeMdOL:b-85zrxm) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L60)):*
> ```Python
> 
> 
> setup(name="pytorch_bigtable", version="0.0.1", author="Google",
> ```

@dopiera Should I change the author to something else too?
___
*[plugin/setup.py, line 61 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MkqxeuyAjwKdOSZQsXi:-Mkvejo127cUZGDGGOS8:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L61)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> support@gmail.com
> ```
info@unoperate.com?
</blockquote></details>

Done.
___
*[Dockerfile, line 15 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkqui7e3f3DQr04lFD0:-Mkvd81NAYXtEKLrgJe0:bs7wumx) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/Dockerfile#L15)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This is all great, but as we spoke, you probably want to retain the ubuntu image as well for `clang-format` and `clang-tidy`.
</blockquote></details>

Done.

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/28)* status: 0 of 17 files reviewed, 7 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/build_wheels.sh, line 1 at r3](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MkvyVt3AfvuskNW2yn8:-MkvyVt3AfvuskNW2yn9:bwjwi1h) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/cbca844d55d3c8e77815166189c2de23f594d538/plugin/build_wheels.sh#L1)):*
> ```Shell
> OUTPUT_DIR="dist"
> ```

Please add:
* the copyright header
* shebang
* set -e -u -o pipefail

Also, it's not a great practice to make the output of the script depend on which working directory you run it from. Please make the `OUTPUT_DIR` depend on the location of the script rather than on the current working directory.

Also, please quote all variables.
___
*[plugin/setup.py, line 31 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkqw8VXEt1pZCLhhEU_:-Mkw-2EVCHUU9lhxoe5Y:b22lnoz) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L31)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

If its not worth the effort, should we do it or not? If we're going to perform some sophisticated logic, just to arrive at the conclusion that we have to copy the same two files, maybe we should just skip it? Especially because I don't see a reason why the list of these libraries that we need to include would ever grow. 
</blockquote></details>

Les't ignore it.
___
*[plugin/setup.py, line 39 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MkqxMxdAgsuE5kP4Dx2:-Mkw-8cFCdW-bv2lQzYB:bye2qar) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L39)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

I did.

I don't even have a way to test it on windows and I presume the whole build process will have to change. 
We support only linux for now, so maybe it will be worth changing it when we actually start supporting windows?

Or I can add:
```
if os.name != 'posix':
     raise Exception()
```

WDYT?
</blockquote></details>

I'd leave it as is.
___
*[plugin/setup.py, line 60 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkveqcy9VB8gdNeMdOK:-Mkw-IsNEv--ZuI9hDof:b-g6hjou) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L60)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

@dopiera Should I change the author to something else too?
</blockquote></details>

That's a question we should ask on today's meeting.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/28)* status: 0 of 17 files reviewed, 6 unresolved discussions (waiting on @dopiera)

___
*[plugin/build_wheels.sh, line 1 at r3](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MkvyVt3AfvuskNW2yn8:-Ml3VXwh9GJh4soEAWNW:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/cbca844d55d3c8e77815166189c2de23f594d538/plugin/build_wheels.sh#L1)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please add:
* the copyright header
* shebang
* set -e -u -o pipefail

Also, it's not a great practice to make the output of the script depend on which working directory you run it from. Please make the `OUTPUT_DIR` depend on the location of the script rather than on the current working directory.

Also, please quote all variables.
</blockquote></details>

Done.
___
*[plugin/setup.py, line 31 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-Mkqw8VXEt1pZCLhhEU_:-MkwPtOV8Dpbo5i6WIKI:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L31)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Les't ignore it.
</blockquote></details>

Done.
___
*[plugin/setup.py, line 39 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MkqxMxdAgsuE5kP4Dx2:-MkwPwPg2U6ovCOI9Jvu:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/73d1c66c8e892d613ba960e57b5a34f3e45ba020/plugin/setup.py#L39)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I'd leave it as is.
</blockquote></details>

Done.

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/28)* status: 0 of 17 files reviewed, 3 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/build_wheels.sh, line 21 at r5](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MlABi7l1II1ebuFtpIU:-MlABi7l1II1ebuFtpIV:b-hz5dun) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/b83289d9babc9adc92e9c57545b5b4e17f3996d4/plugin/build_wheels.sh#L21)):*
> ```Shell
> ROOT_DIR=$( cd "$( dirname "$0" )" ; pwd )
> cd "$ROOT_DIR"
> OUTPUT_DIR="$ROOT_DIR/dist"
> ```

Actually, here, the double quotes are redundant (`sh` is awkward)
___
*[plugin/build_wheels.sh, line 25 at r5](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MlABp2T0euTkbcD4QWH:-MlABp2T0euTkbcD4QWI:bd1ycgl) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/b83289d9babc9adc92e9c57545b5b4e17f3996d4/plugin/build_wheels.sh#L25)):*
> ```Shell
> for python_path in $(find /opt/python/ | grep "cp3[6|7|8|9]")
> do
>   $python_path/bin/pip install torch==1.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
> ```

Please add the double quotes here. Imagine what would happen if someone placed a file in /opt/python called `"rm -rf #"`. Same for all further lines in this file.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/28)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @dopiera)

___
*[plugin/build_wheels.sh, line 21 at r5](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MlABi7l1II1ebuFtpIU:-MlAFk8IDfl5hFeerluJ:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/b83289d9babc9adc92e9c57545b5b4e17f3996d4/plugin/build_wheels.sh#L21)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Actually, here, the double quotes are redundant (`sh` is awkward)
</blockquote></details>

Done.
___
*[plugin/build_wheels.sh, line 25 at r5](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MlABp2T0euTkbcD4QWH:-MlFo3rHAU1-unUIobRV:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/b83289d9babc9adc92e9c57545b5b4e17f3996d4/plugin/build_wheels.sh#L25)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please add the double quotes here. Imagine what would happen if someone placed a file in /opt/python called `"rm -rf #"`. Same for all further lines in this file.
</blockquote></details>

Done.

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/28)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/build_wheels.sh, line 23 at r7](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MlFo3Dr6NgSTVLlKQFZ:-MlFo3Dr6NgSTVLlKQF_:b-fk8rc1) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c4e1a9f92c9c8e3af1b1d98250a13a7704f1b2c2/plugin/build_wheels.sh#L23)):*
> ```
> 6|7|8|9
> ```
Sorry, I noticed it only now. I think what you want is `[6789]`

And BTW  find "/opt/python" -name "cp3[6789]" seems simpler.
___
*[plugin/build_wheels.sh, line 26 at r7](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MlFn6CmDG70NK-mauVK:-MlFn6CmDG70NK-mauVL:b6n7e5w) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c4e1a9f92c9c8e3af1b1d98250a13a7704f1b2c2/plugin/build_wheels.sh#L26)):*
> ```Shell
> do
>   "$python_path/bin/pip" install torch==1.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
>   "$python_path/bin/python" setup.py bdist_wheel -d $OUTPUT_DIR
> ```

Sorry - `$OUTPUT_DIR` should be quoted too.
___
*[plugin/build_wheels.sh, line 29 at r7](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MlFnpM17YeRijNC1LjA:-MlFnpM17YeRijNC1LjB:b-qs5qbo) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c4e1a9f92c9c8e3af1b1d98250a13a7704f1b2c2/plugin/build_wheels.sh#L29)):*
> ```Shell
> done
> 
> for wheel_file in $OUTPUT_DIR/*
> ```

And here too.

**Review by kboroszko — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/28)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @dopiera)

___
*[plugin/build_wheels.sh, line 23 at r7](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MlFo3Dr6NgSTVLlKQFZ:-MlFrPXt9gOzomCQ42_U:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c4e1a9f92c9c8e3af1b1d98250a13a7704f1b2c2/plugin/build_wheels.sh#L23)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> 6|7|8|9
> ```
Sorry, I noticed it only now. I think what you want is `[6789]`

And BTW  find "/opt/python" -name "cp3[6789]" seems simpler.
</blockquote></details>

Done.
___
*[plugin/build_wheels.sh, line 26 at r7](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MlFn6CmDG70NK-mauVK:-MlFrPvMDexeKg_9kANA:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c4e1a9f92c9c8e3af1b1d98250a13a7704f1b2c2/plugin/build_wheels.sh#L26)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Sorry - `$OUTPUT_DIR` should be quoted too.
</blockquote></details>

Done.
___
*[plugin/build_wheels.sh, line 29 at r7](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MlFnpM17YeRijNC1LjA:-MlFrQLg9lPvIygMp1cu:b-896fix) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/c4e1a9f92c9c8e3af1b1d98250a13a7704f1b2c2/plugin/build_wheels.sh#L29)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

And here too.
</blockquote></details>

Done.

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/28)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[plugin/setup.py, line 66 at r10](https://reviewable.io/reviews/unoperate/pytorch-cbt/28#-MlFuywb3DeQPRhznFl7:-MlFuywb3DeQPRhznFl8:b-2uw69j) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/6835928bd793a32a20f6ddb705918f8916a2526e/plugin/setup.py#L66)):*
> ```Python
>         if lib in line:
>           lib_loc = line.split()[2]
>           os.system(f"cp {lib_loc} {lib_dir}")
> ```

Sorry, I noticed it only now, please use some python library, e.g. `shutil.copyfile()`.

The way it's written, it will fail on any white space in the file names (and it has an unneeded requirement of this being UNIX).

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/28)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @dopiera)

**Pull request merged**
